### ISSUE TITLE
tabris.js support in Dirigible trial

### ISSUE THREAD

**Issue by kc853** [dirigible-io/dirigible-io.github.io#40]
Hello,
is ist possible to intergrate tabris.js support in the Dirigible trial instance on http://dirigible.eclipse.org/ ?
I'd really like to follow the turotial in this blog 
http://www.dirigible.io/blogs/2016/02/05/blogs_develop_from_mobile_for_mobile.html

**Comment by delchev** [comment]
Hello kc853,

Thanks a lot for showing interest on Tabris.js integration of Eclipse Dirigible!
I created an issue under Dirigible's project repository:
https://github.com/eclipse/dirigible/issues/276
and somebody from the team will start working on it soon.
Do you want to contribute afterwards more templates related to mobile applications with Tabris?

Regards,
Nedelcho

**Comment by kc853** [comment]
That's great! Not shure about my skills to contribute right now... But let's wait and see.
Regards.

**Comment by delchev** [comment]
Hi kc853,

The new Tabris v2 based template is available on the Trial instance. Please, verify whether it is working correctly on your side.
In case of issues, please open bugs directly here - https://github.com/eclipse/dirigible/issues

Regards,
Nedelcho
